### ISSUE TITLE
Show outdated modules

### ISSUE THREAD

**Issue by bugsounet** [KristjanESPERANTO/MagicMirror-3rd-Party-Modules#20]
Hi, Kristjan

maybe with `Show outdated modules` is better to not check it by default ?

**Comment by KristjanESPERANTO** [comment]
Would it also be okay to work with a URL parameter? If you include the following URL, the old modules will not be displayed: https://kristjanesperanto.github.io/MagicMirror-3rd-Party-Modules/?showOutdated=false

Somehow I see advantages in both options (showing and not showing) and I don't know which is really better.

I imagine the following scenario, which is why I tend to show the outdated modules by default: A user is looking for a module, but there is none "normal" module, but there is one outdated. The user looks at the module and adapts it to his needs and is happy. If we were to hide the outdated modules, the user might not be able to find the outdated module which helped him.

**Comment by KristjanESPERANTO** [comment]
Because of the URL parameter I think I can close this issue :slightly_smiling_face:
