### ISSUE TITLE
Specifying correct image?

### ISSUE THREAD

**Issue by dathbe** [KristjanESPERANTO/MagicMirror-3rd-Party-Modules#23]
How can developers specify which image will show up as the thumbnail for their module?  For example, MMM-MoonPhase has two images, `./images/2019-06-22-example-moons.png` and `./images/2023-09-15-example-moons.png`.  The first was chosen as the thumbnail, but the second is the better representation of the module.  

Also MMM-MyScoreboard

**Comment by KristjanESPERANTO** [comment]
The README describes it like this:

> If there are several images in your repository, one image is selected according to the following logic: First search for an image that contains 'screenshot' or 'example' in it's name and if none is found, take the first image that is found.

But does not describe what happens if there are two files with `example` in the name. Then the first file containing `example` is  taken. As 2019 comes before 2023, the 2019 image is used.

Spontaneously I have the following suggestion. Rename the files as follows:

- `2019-06-22-example-moons.png` -> `example_2_moons_2019-06-22.png`
- `2023-09-15-example-moons.png` -> `example_1_moons_2023-09-15.png`

**Comment by dathbe** [comment]
I want to make sure the image is only referenced in the one place in the README (I couldn't find a reference to the 2019 file, so I'm wondering if they are referenced elsewhere).  Then I'll open a PR on the module's repo.

**Comment by dathbe** [comment]
I just added a new copy of the image and called it example.png.  What's an extra 4kb.
