### ISSUE TITLE
GitHib stars

### ISSUE THREAD

**Issue by bugsounet** [KristjanESPERANTO/MagicMirror-3rd-Party-Modules#32]
Hi Kristjan,

It seems to me that the GH stars are no longer updated.

Example:

![image](https://github.com/user-attachments/assets/668641f4-34cc-4616-840d-6e400adb3a4a)
![image](https://github.com/user-attachments/assets/ca36d428-6a56-49fa-9914-ef1bef4ce4a3)

[gitHubData.json](https://github.com/KristjanESPERANTO/MagicMirror-3rd-Party-Modules/blob/main/docs/data/gitHubData.json#L4680-L4693)  returns wrong information?

**Comment by KristjanESPERANTO** [comment]
Sorry for the late reply!

The API only allows a limited number of queries, which is why it sometimes takes over a week to update the data. So far, I have not considered the delay to be tragedy.

Now it matches again for your module :slightly_smiling_face: 

But please let me know if you notice any major discrepancies!
